### ISSUE TITLE
[Info] App version push

### ISSUE THREAD

**Issue by ThibautSF** [ThibautSF/ParadoxosModManager#11]
I push the beta 0.4.0 :)

Documentation and Version Log edited.

**Comment by NicolasGrosjean** [comment]
Thanks and congratulations

**Comment by NicolasGrosjean** [comment]
You can create a release on GitHub if you want to know how to do.
Besides it is practical because all the commit will have the indication of the release they appear.

**Comment by NicolasGrosjean** [comment]
Personnally, I will put the GitHub download link in my Blog on reseau-js.
I find it is more convenient to click and your browser asks you what do you want with this (open or download).

**Comment by ThibautSF** [comment]
It's interesting to put the github link for peoples who wants to try in dev version. It just that we have to use Google Drive for stable versions because GitHub links aren't allowed on the forum ParadoxPlazza (like many other things... :( )

I think, since we have a version checker with 0.4.0, we can create more posts on different forums, because we will not have to inform new version :)

**Comment by NicolasGrosjean** [comment]
GitHub links are forbidden for mods (to fight against piracy and build communities on their forum).
I am not sure it is also the case for application.

The 2 French forum with active communities in the Paradox Big 4 for which I have not done advertising yet is Mundus et JeuxVideo.com

**Comment by ThibautSF** [comment]
In one of the app thread, a forum user proposes to put the project on GitHub, and a moderator says that GitHub links were not allowed...
