### ISSUE TITLE
[Major] Mod files not found (custom doc path)

### ISSUE THREAD

**Issue by ThibautSF** [ThibautSF/ParadoxosModManager#12]
A bug reported by kriiks (https://forum.paradoxplaza.com/forum/index.php?members/kriiks.987176/)

His description : 

> Hello, is is still managed? I was so happy to find that there is mod manager for Stellaris and then so disappointed when I found out that it can't read mod info for whatever reason. Even if it seems to find my mods (Mods found: 61), if i try to create modlist, I just see MOD MISSING errors all over.

> Instead of default "C:\Users\NAME\Documents\Paradox Interactive\Stellaris\" path I'm using "D:\My Documents\Paradox Interactive\Stellaris". 
Mods what are found are certainly located at D: drive and Mod Manager is showing right path. I'm only user of this PC (W7) and also admin. Mod Manager itself is located on D: drive too.
Update:
Out of curiosity I tried to copy Stellaris folder to default location on C drive and Manager works with default path! So why doesn't it like my non-default path? I'd prefer keep my Documents folder off from main drive, like it's been last 6 years :)
My friend also tried Mod Manager and couldn't get it to work, but he doesn't use default My Documents path too. So we both have same problem :eek:

It seems i forgot to put/edit the path variable somewhere when i add this option to use another document dir folder than default one...

**Comment by ThibautSF** [comment]
After a check it don't seems to be the path...

What the user have : http://prnt.sc/f4gwdh
What i have : http://prnt.sc/f4mjft

I ask his mod/ folder to check if it's the .mod files ...

**Comment by NicolasGrosjean** [comment]
It is strange.

P.S : You can directly put the image on GitHub issues by drag and drop

**Comment by ThibautSF** [comment]
I know for images ^^ It just that they come from a PM discussion on ParadoxPlazza which doesn't allow images in MP...

**Comment by ThibautSF** [comment]
Ok i found the origin, the file separator isn't correctly added to the path when the Mod and ModList are generated ! So if user put "<path>\Stellaris" as modified doc dir, the app try to open files with ""<path>\Stellarismod\<file>".

I will fix that after sleep because i'm too tired to try to find why the file sep isn't here ^^ i PM the player who submit the bug so he know he have to add "\" to the path before we push 0.4.1.

**Comment by ThibautSF** [comment]
Now i will be able to sleep ^^ (and i see that if i put "Fix #<number>" for a commit it's auto-close the issue...)

**Comment by NicolasGrosjean** [comment]
Yes, you have the full list of closing keywords [here](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by ThibautSF** [comment]
Thanks :)
