### ISSUE TITLE
My Little ToDoList

### ISSUE THREAD

**Issue by ThibautSF** [ThibautSF/ParadoxosModManager#16]
1. Update the code structure
Target package structure :
application → UI (ModManager, ListManager, ListCreator)
mod → objects use for mod management (Mod, ModList, Languages)
settings → mod list and app settings management (MyXML → maybe split in two objects AppSettingsXML and ModListXML for example)
debug → test classes and errors (ErrorPrint, test classes with main(), Exceptions classes...)
versioning → version checker (integration and adaptation of your very good improvements with update infos and logs :) )

2. Comment the code / javadoc because it become hard to remember which function do what, and it will make the code more clear for everyone

3. Update ListManager UI with TableView instead of ListView (like in ListCreator), in order to add options to sort/order mod lists.

4. Need to work also on UI resize (the problem with gap values in percents...)

**Comment by ThibautSF** [comment]
So update structure almost done (i keep the actual MyXML for now...)

Reintegration of @NicolasGrosjean improvements of versioning system made for [Translate Helper](https://github.com/NicolasGrosjean/Translate_helper). Add improvements (see changelog of all versions between the local one and the online one), and adapt to Paradoxos versioning and UI.

![image](https://user-images.githubusercontent.com/9386581/36934092-191535dc-1ee4-11e8-9c6c-615e7c4cf5b9.png)
First button → https://github.com/ThibautSF/ParadoxosModManager/releases
Second → https://github.com/ThibautSF/ParadoxosModManager/releases/tag/0.5.2
Third → Direct download
Last → Ignore update

**Comment by NicolasGrosjean** [comment]
If you think that there is too much options, the best will be replace the first three by an "automatic" update.
Click on this action will launch a new application which download the zip, extract new files and replace the old one by the new (that's why it should be another application).

**Comment by ThibautSF** [comment]
Yeah...
I was already a bit thinking about auto update for option "Get Update", it can be interesting to dev, i will look that ^^

For now i will remove the "See x.x.x" :D
Will keep "All versions" (for all release version), "Get Update" for the last version zip, "Continue".

**Comment by ThibautSF** [comment]
Now it's a TableView, and it's will be better (but not easier ^^) for future improvements.

![image](https://user-images.githubusercontent.com/9386581/37223535-25f034ea-23d1-11e8-8dec-411db1b09a94.png)

**Comment by ThibautSF** [comment]
Like you suggest, "Automatic" update is here !

Still need to work on the download/update window design.
Here an archive to test (it's the last version with the updater but version flag as 0.4.2)
[ParadoxosFalseOldVersion.zip](https://github.com/ThibautSF/ParadoxosModManager/files/1798943/ParadoxosFalseOldVersion.zip)

**Comment by NicolasGrosjean** [comment]
I have a compilation issue

![image](https://user-images.githubusercontent.com/13560473/37257427-605e907e-2569-11e8-92a5-cf83e08077af.png)

**Comment by NicolasGrosjean** [comment]
The window is too small

![image](https://user-images.githubusercontent.com/13560473/37257523-dcbcdf3a-256a-11e8-99dd-117527131033.png)

**Comment by NicolasGrosjean** [comment]
I have an issue, after updating I have in fact an old version ...
![image](https://user-images.githubusercontent.com/13560473/37257604-2b535e20-256c-11e8-85c1-5fc05af4eee8.png)

**Comment by ThibautSF** [comment]
After update you should get the 0.5.2 (because it's the last public version)

For the window size i planed to improve size and UI, i don't use dialogue because i needed a stage i can control (for the background download). I will try to make a custom Dialog class.

**Comment by ThibautSF** [comment]
Main windows has much better resize effect
Tested for ListManager, supposed ModManager because resize is blocked (reason unknown)

Ready for 0.6.0 here.
