### ISSUE TITLE
Conflicts warnings

### ISSUE THREAD

**Issue by NicolasGrosjean** [ThibautSF/ParadoxosModManager#18]
[Someone asked again about a conflict determination feature.](http://forum.paradoxplaza.com/forum/index.php?threads/tool-paradoxos-mod-manager.1001307/page-2#post-23976757)

[I have seen that you have already talked about](http://forum.paradoxplaza.com/forum/index.php?threads/tool-paradoxos-mod-manager.1001307/#post-22571217).
Now with plenty of mods in the workshop it can be very interesting feature.

A warning when 2 mods modify the same file can be a first good iteration.

**Comment by NicolasGrosjean** [comment]
The conflict doesn't work on compressed mods, because the Java API doesn't support the compression method used by Steam ...
https://stackoverflow.com/questions/24368236/how-to-determine-the-compression-method-of-a-zip-file

**Comment by NicolasGrosjean** [comment]
Now I have performance issues.
Computing the list of the modified files of all the mods is relatively expensive.

The problem is that the application does it at each Windows focus !
![image](https://user-images.githubusercontent.com/13560473/37988970-7eb071e6-3202-11e8-8f1f-20e53f69174f.png)

I don't know what is the goal of this updateList.

There are also some useless Mod creation like when creating ListCreator.
The mod objects need to be created once.

**Comment by NicolasGrosjean** [comment]
I have done the refactoring, now the Mod constructor is only called in ListManager#loadModFilesArray

**Comment by NicolasGrosjean** [comment]
Things to improve : 
- add a progress bar for the Mod object creation
- sort the conflict files
![image](https://user-images.githubusercontent.com/13560473/37990751-778bc80c-3207-11e8-97e2-d0bb24179979.png)

**Comment by ThibautSF** [comment]
Ok, i saw conflict loading is very heavy... (up to 1min for my 178 installed mod on Stellaris)

So i agree we need a ProgressBar. It can be shown in a loader window (usefull for the first loading). This should be interesting : http://blog.carl.pro/2016/05/modal-jaxafx-progress-indicator-running-in-background/
(and maybe also for the app updater)

Another solution (maybe) : 
- Don't load conflict at start/reload
- Make a button which generate/update the conflicts
Advantage : Fast use when you just want to apply a list and play (or make simple edits)
Inconvenient : More action to do if you want to use the conflict option


Bugs & improvements : 
![image](https://user-images.githubusercontent.com/9386581/37996393-c8a77136-3217-11e8-8390-c16060635208.png)
I've got 2 conflicts : "(-NSC2 Addon: Unlimited Supercapitals-)" and "(-NSC2 Season 1 - Episode 3 - v1.3-)". If i remove one mod, the other stay in orange.
The new color also reveal a coloration bug after list scroll (orange become green again)
Just need those little modifications of this old code : 
![image](https://user-images.githubusercontent.com/9386581/37996486-1b8877c4-3218-11e8-890d-bb4258a7677c.png)

I don't think ExpandableContent is useful since user will always expand
![image](https://user-images.githubusercontent.com/9386581/37996890-8ce2bbae-3219-11e8-976b-c65d37188a1a.png)
Just put `setContent(expContent)` instead of `setExpandableContent(expContent)` (line 643)

**Comment by ThibautSF** [comment]
Seriously ! Even "fixed" close issue !

**Comment by ThibautSF** [comment]
> 2018-03-28 13:55:41 : type ERROR MESSAGE
Unable to unzip /home/tsimonfine/.local/share/Paradox Interactive/Stellaris/workshop/content/281990/1219685453/hivefocus.zip

**Comment by ThibautSF** [comment]
```
2018-03-28 13:55:41 : type ERROR MESSAGE
Unable to unzip /home/tsimonfine/.local/share/Paradox Interactive/Stellaris/workshop/content/281990/1219685453/hivefocus.zip
```
If a zip file is missing it make the app crash.

**Comment by ThibautSF** [comment]
I work on the "loader window" from http://blog.carl.pro/2016/05/modal-jaxafx-progress-indicator-running-in-background/
Functional version (but i don't think it's stable/optimal for now).

Very low battery so i push my progression (add some 'TODO' tag)
Need tests, if unstable comment/uncomment 'newloadModFilesArray()'/'loadModFilesArray()'

**Comment by NicolasGrosjean** [comment]
> Solution to performance issue

Yes by default we need to NOT compute the conflicts.
I was thinking about a checkbox to enable it when selecting the game, but an action to compute conflicts seems better because you can update.

> Bugs

Thanks for fixing my bug, I have bad insert my code in your for the coloration, and I have done a bad copy-paste for the Dialog

> If a zip file is missing it make the app crash.

I will fix it, I have the stack trace
`java.lang.NullPointerException
	at mod.Mod.addModifiedFiles(Mod.java:189)
	at mod.Mod.setModifiedFiles(Mod.java:136)
	at mod.Mod.<init>(Mod.java:70)
	at mod.Mod.<init>(Mod.java:41)
	at tests.TestMod.modifiedFilestest(TestMod.java:47)`

> Error generated also if file is here

I don't understand what is the use case. The .mod file is incorrect ?
I will catch the exception

**Comment by NicolasGrosjean** [comment]
> Functional version (but i don't think it's stable/optimal for now).

I have a NPE : 
java.lang.NullPointerException
	at mod.ModList.computeConflicts(ModList.java:203)
	at mod.ModList.<init>(ModList.java:37)
	at settings.MyXML.getSavedList(MyXML.java:154)
	at application.ListManager.updateList(ListManager.java:481)

I can continue to develop despite it

**Comment by ThibautSF** [comment]
Still working on wait window :)
![image](https://user-images.githubusercontent.com/9386581/38053131-916a3f70-32d3-11e8-8376-e2fb679b727d.png)

**Comment by NicolasGrosjean** [comment]
> Don't know where we can put WorkIndicatorDialog ... maybe a "dialog" package...

In a dialog package with BasicDialog seems a good idea 

> java.util.zip.ZipException: invalid compression method

I have it on each zip file ... Java didn't support the compression of the .mod file which is in each zip directory.
I will check if some files are missing or not

**Comment by NicolasGrosjean** [comment]
No modified files are missing because the directories are browse deeply and the mod file is in root.

**Comment by ThibautSF** [comment]
Forgot to put the # in the last commit...

**Comment by NicolasGrosjean** [comment]
I see that I have done a commit with message "Fix NPE #18" and the issue hasn't been closed.

**Comment by ThibautSF** [comment]
I'm a bit jealous...

**Comment by NicolasGrosjean** [comment]
In fact if you put some words between fix (and other synonymous) and the issue number, it don't close the issue

**Comment by ThibautSF** [comment]
I add some opacity (i have a problem with the size, the upper window is a bit bigger)
![image](https://user-images.githubusercontent.com/9386581/38055393-e5089c0c-32d9-11e8-9cee-429b708a93cf.png)

**Comment by ThibautSF** [comment]
Due to window decoration i use scene width and height... Maybe i can remove a fixed margin...
![image](https://user-images.githubusercontent.com/9386581/38057169-d5cc4db0-32de-11e8-85dc-eb23ae213e46.png)

**Comment by ThibautSF** [comment]
The option
![image](https://user-images.githubusercontent.com/9386581/38091241-3d8f75c2-3365-11e8-9f3d-73323c0a5c02.png)

This option is stored in the ModManager.APP_PARAMS Map<String,String>, with key `DetectConflict`.
```
if(ModManager.APP_PARAMS.containsKey("DetectConflict")){
	if(ModManager.APP_PARAMS.get("DetectConflict").equals("true"))
		//Do conflict stuff
}
```
The text in the loading window screen already implements the code. So you can put the test where you want.

**Comment by NicolasGrosjean** [comment]
I have enclosed it in a static method it is more readable.

I have noticed that when saving I remove some useless import. I advise you to use this Eclipse preference to remove useless imports and so reduce the Jar size.
![image](https://user-images.githubusercontent.com/13560473/38103551-e2ffd9e0-3386-11e8-981f-af90736cdef6.png)

When you need to import one class, you can do Ctrl+Shift+O.

I have discovered these tips recently

**Comment by ThibautSF** [comment]
It's good for me.

**Comment by NicolasGrosjean** [comment]
Ok, I will test this evening and like you have said in another issue, we can create a new version.

**Comment by NicolasGrosjean** [comment]
Bug : 

We cannot deselect mods with conflicts

**Comment by ThibautSF** [comment]
I remove other list.removeMod() and list.addMod(), so I need to replace them.

**Comment by NicolasGrosjean** [comment]
Thanks.

Bug in the conflict display between CK2 mods WtWSMS and BLG : 
![image](https://user-images.githubusercontent.com/13560473/38161577-ca70a066-34d1-11e8-8a5a-74d239d66d2f.png)

**Comment by ThibautSF** [comment]
Yeah it's caused by the auto wrap, because the line contains one "word" : the path
"\tPATH" so the textarea wrap : 
```
\t
PATH
```

**Comment by NicolasGrosjean** [comment]
You agree the word is too long so textArea has wrapped it.

So I will set wrapping to false (another bad copy-paste)

**Comment by ThibautSF** [comment]
From : https://forum.paradoxplaza.com/forum/index.php?threads/tool-paradoxos-mod-manager.1001303/page-3#post-24039672

```
What I noticed is that many conflicts stem from the fact that many mods have a 'changelog.txt', 'description.txt', 'readme.txt' or some other generic file in them which are named the same but should not impact gameplay (afaik). Would it be able to add a whitelist for file names which are excluded from the conflict check?
```

Maybe files in the mod's root directory can be skiped ?

**Comment by NicolasGrosjean** [comment]
Thanks you for the copy paste, I have not access to the Stellaris forum.

I have also observed this phenomenon on mods done by the same person but I have conclude it should be rare. Or I simply wait that somebody report this.

Like you, my idea to counter this was to filter files in the root directory.
I will implement this.

**Comment by NicolasGrosjean** [comment]
I close this issue like the development is delivered in 0.6.0.
