### ISSUE TITLE
ListManager and MyXML refactor cause errors with missing mods

### ISSUE THREAD

**Issue by ThibautSF** [ThibautSF/ParadoxosModManager#19]
We still need to generate fake Mod (with filename and remoteID) and set isMissing to true in availableMods.
Conflict compute have to ignore missing mods.

**Comment by NicolasGrosjean** [comment]
With 4d5b9d3c, I have this : 
![image](https://user-images.githubusercontent.com/13560473/38108963-c6470836-3396-11e8-8bb5-ae049156e9e6.png)

**Comment by ThibautSF** [comment]
Hmmm... In this version there is

```
Mod oneMod = availableMods.get(fileName);
if (oneMod == null) {
    oneMod = new Mod(fileName, false);
}
listMods.add(oneMod);
```

but my version have
```
Mod oneMod = availableMods.get(fileName);
listMods.add(oneMod);
```

Manip error somewhere ? :thinking:

**Comment by NicolasGrosjean** [comment]
You need to refresh with Eclipse after pulling, maybe.

**Comment by ThibautSF** [comment]
For mod name it was supposed...

Old XML
![image](https://user-images.githubusercontent.com/9386581/38109603-f60a8014-3398-11e8-9eea-07528faa150a.png)

Recent : 
![image](https://user-images.githubusercontent.com/9386581/38109633-0985e818-3399-11e8-8e62-5eb6a8d3781e.png)

**Comment by NicolasGrosjean** [comment]
The constant MOD_NAME is still used.

2 options : 
- We remove it
- We add it again

**Comment by ThibautSF** [comment]
Ok, the mod name is added only when list is modified...
![image](https://user-images.githubusercontent.com/9386581/38110153-fda2f908-339a-11e8-8b4a-598e0e6dd524.png)

I will refactor that. There is too much similar code.
