### ISSUE TITLE
Missing mod in a configuration

### ISSUE THREAD

**Issue by NicolasGrosjean** [ThibautSF/ParadoxosModManager#3]
I have done a configuration with 6 mods

![image](https://cloud.githubusercontent.com/assets/13560473/25086247/d20251ee-2366-11e7-91de-14ccbbcbd092.png)

One mod doesn't appear in the game launcher

![image](https://cloud.githubusercontent.com/assets/13560473/25086226/b6185b9a-2366-11e7-85f1-1e938c3a0f7b.png)

However, it appears in the settings file
![image](https://cloud.githubusercontent.com/assets/13560473/25086309/265865da-2367-11e7-9eff-05887b62d864.png)

Before to use the Paradoxos Mod Manager, the settings file was
![image](https://cloud.githubusercontent.com/assets/13560473/25086325/43409280-2367-11e7-85c5-7e22166643ce.png)

I remark there is no { } in the text generated by the application

**Comment by NicolasGrosjean** [comment]
I confirm, if I add manually the { }, the bug is solved

**Comment by NicolasGrosjean** [comment]
I have fixed the bug for Crusader Kings 2.

@ThibautSF I have neither HoI 4 neither Stellaris to test if I have broken something

**Comment by ThibautSF** [comment]
I test for Stellaris and HoI 4, i don't see any problems.

**Comment by NicolasGrosjean** [comment]
In fact I have created a bug on CK2.
See this settings file
![image](https://cloud.githubusercontent.com/assets/13560473/25150238/8883f9e8-2481-11e7-80bd-e6e749c7ade8.png)

**Comment by ThibautSF** [comment]
I will re-test for Stellaris and HoI this afternoon.
