### ISSUE TITLE
Incompatibility with Java 10

### ISSUE THREAD

**Issue by NicolasGrosjean** [ThibautSF/ParadoxosModManager#32]
A user reports me that the Paradoxos Mod Manager doesn't work with Java 10.

[Now Oracle proposes Java 10](http://www.oracle.com/technetwork/java/javase/downloads/index.html).

**Comment by NicolasGrosjean** [comment]
`Exception in thread "JavaFX Application Thread" java.lang.NoClassDefFoundError: com/sun/javafx/css/parser/CSSParser
	at de.jensd.fx.glyphs.GlyphIcon.<clinit>(GlyphIcon.java:49)
	at application.ListCreator$MultipleButtonCell.<init>(ListCreator.java:699)
	at application.ListCreator$6.call(ListCreator.java:289)
	at application.ListCreator$6.call(ListCreator.java:1)`

**Comment by NicolasGrosjean** [comment]
[Like fontawesomefx doesn't work in both Java 8 and 10 (in fact also 9)](https://bitbucket.org/Jerady/fontawesomefx/issues/55/incompatible-with-java-8#comment-46038660), I will push the fix for Java 10 in a new branch.
So we should release a dedicated version for Java 10.

**Comment by NicolasGrosjean** [comment]
38e7884654c32fb2b1ad0bc046c05571ece0fe9b

**Comment by ThibautSF** [comment]
Need to remember that java 9 & 10 are short time support version.
Java 9 is no longer updated&supported. And 10 is close to end.

http://www.oracle.com/technetwork/java/javase/eol-135779.html

**Comment by NicolasGrosjean** [comment]
Ok I have forgotten this.

The user tells me that there is some mods in Java 10 for Minecraft and he cannot come back to Java 8.

I have lost my time ...

**Comment by ThibautSF** [comment]
In fact, i chated with Ael's, i think that for similar cases we could release a version with a packed JRE (don't wanted before because i have a bad upload speed ^^).

But since we have got the auto updater, we could release a version with jre and next the updater will make his role.
