### ISSUE TITLE
Unable to make a new List

### ISSUE THREAD

**Issue by MinerMax555** [ThibautSF/ParadoxosModManager#33]
When I try to make a new list, nothing happens besides the following stacktrace appearing in the console:
[stacktrace.txt](https://github.com/ThibautSF/ParadoxosModManager/files/2151706/stacktrace.txt)

Interestingly enough, when I start the cloned project in the Eclipse IDE, everything works fine

**Comment by ThibautSF** [comment]
The one time i had the same bug was when i launched the app with JRE 10. 
Are you sure that you use JRE 8 ?

**Comment by MinerMax555** [comment]
I might have used JRE 10. Is that not supported yet?

**Comment by ThibautSF** [comment]
We doesn't plan to support JRE 10 (like 9) because they are short time support version.
JRE 8 only is supported.
We will try to support JRE 11 as soon as possible after Java 11 release.
