### ISSUE TITLE
Online new version checker

### ISSUE THREAD

**Issue by ThibautSF** [ThibautSF/ParadoxosModManager#4]
One major update i want to do :
The app check at launch if a new version is available (if a new version is found -> info dialog with link to the repository).

But i don't know how to do this (where to stock the actual app version online)...

Maybe we can access to a file stocked on github and get this current app version...

**Comment by ThibautSF** [comment]
Yeah ! Double commit ! ^^

If you can test that. When #1 is ready i think we can push a 0.4.0 :)

**Comment by ThibautSF** [comment]
Can you send me your email (Steam or tsimonfine@gmail.com) so i can add rights to modify the Google Drive of the app ;)

**Comment by NicolasGrosjean** [comment]
Thanks

**Comment by ThibautSF** [comment]
There is still a bug... my "if" is not good. I correct that ASAP.

Can you start to update the documentation ?

**Comment by NicolasGrosjean** [comment]
Sorry I have missed your comment about documentation.
Maybe I have seen only your commit.

**Comment by ThibautSF** [comment]
No problem ^^

I make edit of documentation, if you find something wrong or want to add something, feel free.
