### ISSUE TITLE
Mods not detected while in Active Conflict Detection mode

### ISSUE THREAD

**Issue by ClaudeJanssenPro** [ThibautSF/ParadoxosModManager#43]
It seems that the Active Conflict Detection mode might struggle to detect mods when there several thousand of them in the docs folder.
Eg. : I do now have 268 mods in my HOI4 docs folder and loading with the Active Conflict Detection mode checked on, only about 255 were detected.
All were using the default loading mode.

- Could larger mods be left out the comparison? Eg. music mods are quite large and I don't really need to have them compared to, for example, gameplay mods.

**Comment by ThibautSF** [comment]
Does PMM generate a DebugLog.txt file ?

**Comment by ClaudeJanssenPro** [comment]
(no sweat)

None that I can find.

A workaround I found is to start the Paradox's launcher as before, let it detect new mods, close it then start PMM.

The more I have mods, the more PMM is useful by the way.

**Comment by ThibautSF** [comment]
So I suppose that mods not detected by PMM were just without any .mod file.

PMM don't replace the Paradox logic when you add mods (through Steam Workshop). So when a new mod is downloaded with steam, mod fil need to be generated by the game launcher.
i.e. just launch the launcher, exit, and then launch PMM (or use the refresh button in the list manager view)

**Comment by ClaudeJanssenPro** [comment]
Got it, thanks for the explanation.

**Comment by ClaudeJanssenPro** [comment]
Got it, thanks for the explanation.
The issue is not then, thus it can be closed.
