### ISSUE TITLE
my dude, stellaris gets a new update that changed the launcher

### ISSUE THREAD

**Issue by randomguyingithub** [ThibautSF/ParadoxosModManager#49]
and thus the mod manager doesn't work.

**Comment by ThibautSF** [comment]
Thanks,

I plan to work on that (EU IV as well) this WE

**Comment by ThibautSF** [comment]
Keep here infos linked on Stellaris Modding Den by @McAwesome 

> Info about the new launcher
https://forum.paradoxplaza.com/forum/index.php?threads/launching-the-new-launcher-coming-with-1-29-manchu.1245872/

**Comment by ThibautSF** [comment]
[ParadoxosModManager0.8.0BETA.zip](https://github.com/ThibautSF/ParadoxosModManager/files/3719656/ParadoxosModManager0.8.0BETA.zip)

Beta version for Stellaris and EU4 new launcher

**Comment by 9bananas** [comment]
Hi ThibautSF! what is the 2.4 launcher supposed to do? when i open the paradox launcher, nothing seems changed...? the new launcher doesn't seem to change mod order in the paradox launcher.

also: one of my mods doesn't activate, even though it's active in the modlist?

**Comment by ThibautSF** [comment]
I don't edit Launcher order because it will need much more complex work to add and I have barely the time to maintain this tool :c 
Continue in #50
