### ISSUE TITLE
[Question][Feature Request] Applying Load Order to the new Paradox v2 Launcher?

### ISSUE THREAD

**Issue by 9bananas** [ThibautSF/ParadoxosModManager#50]
Load order doesn't currently seem to be saved to the new launcher.
There's nothing i saw in the documentation about how exactly mod order is applied in the new launcher:

I'd like to know which specific file(s) is(are) being written to: i assume it's supposed to be "mods_registry.json", but that one doesn't seem to change.

Is the mod order still applied by changing the mod names in the description.mod files?
If so, then that seems obsolete now, because of the new launcher (which sucks..)

could you provide more information on the details about this?

It doesn't currently seem like paradox is in any hurry to fix the launcher, so this is my only hope at getting the game running again. There's no way i'm sorting ~175 mods by hand...

**Comment by ThibautSF** [comment]
For the new launcher :
Default sorting order applied for the list should be the same as the legacy, but won't see the modification in the launcher because I don't edit "mods_registry.json".

When you apply a list and start the launcher, you should not try to add/remove a mod through the launcher because it will reorder all the activated mods with the launcher order. Normally, just launch the game and it will keep the order in "dlc_load.json"

**Comment by 9bananas** [comment]
great, thank you!

might want to add that to the documentation, if you haven't already

cheers!

**Comment by ThibautSF** [comment]
I can give you the write access to the documentation if you want.

I don't really have time to maintain the documentation up to date for now (barely have time for the code ^^')

**Comment by 9bananas** [comment]
i could try to add and clarify a few things, will have to take a look tomorrow as it is getting late!
i can definitely spell check and correct some grammar!

don't know how much time i'll have for maintenance, kinda swamped in university stuff myself right now...

i'll fork the read.me for now, edit it tomorrow. if it turns out i have more time to work on this, i'll let you know! sound good?^^

**Comment by ThibautSF** [comment]
If you want edition right on the Google Doc just ask edit rights I can grant them when I receive the mail: https://docs.google.com/document/d/1wThmbZIEGWzDO3rp8-zzJumebXDBE4-q6L6GnzVKmAY/edit

**Comment by 9bananas** [comment]
will do!
