### ISSUE TITLE
Won't apply mods for 2.5

### ISSUE THREAD

**Issue by TuxuHolyland** [ThibautSF/ParadoxosModManager#54]
I made a list - like always - Applied it but when I run the game it starts with no mods, the official launcher also shows no mods are on.

Am I doing something wrong or is this an actual issue?

tell me where to get you the relevant data from and I will :)

**Comment by ThibautSF** [comment]
Which game (and version)?
If you have a  ̀DebugLog.txt` file in the Paradox Mod Manager folder can you send it. After you apply a list (the file is deleted each time you launch PMM).

Also looks like Paradox change again some things in their launcher...

**Comment by TuxuHolyland** [comment]
Okay, I'll make a batch file to do that automatically for me,

I am using ParadoxosModManager0.7.1 with Stellaris Shelley 2.5.1 (Non-beta)
if pastebin works here then -
<iframe src="https://pastebin.com/embed_iframe/eRTr3cTU" style="border:none;width:100%"></iframe>

if not - 

https://pastebin.com/eRTr3cTU

**Comment by ThibautSF** [comment]
Ok, so you can ignore zip errors, they aren't a problem.

The real error is line 401
```2019-11-05 14:39:54 : type EXCEPTION MESSAGE
Action : When list application
java.io.FileNotFoundException: C:\Users\Tuxu\Documents\Paradox Interactive\Stellaris\dlc_load.json (The system cannot find the file specified)```

Can you check that you have the file `dlc_load.json`?
If not, launch the game launcher and enable a mod (it should create the file) -> I just test and it seems that the launcher doesn't create this file if it is missing (unless you add/remove a mod once)

**Comment by TuxuHolyland** [comment]
There you go.
https://pastebin.com/9cetvHDm

**Comment by ThibautSF** [comment]
OK... I don't understand what could have create the problem and why you can apply now...

**Comment by TuxuHolyland** [comment]
The problem was that I have never launched the game with the new official launcher and so I did not have a `dlc_load.json` file.

I came to relay on your PMM because it is great that I've completely abandoned the official launcher.

I think that you should add to the documentation that Stellaris should be launched at least once with the official launcher with at least one mod activated so that `dlc_load.json` will be created.

Maybe I've missed it(wouldn't be the first) but it didn't say that when I've read the Installation instructions.

**Comment by Perhelion** [comment]
The version 0.7.1 doesn't support load order for Stellaris 2.5.* as the order is stored in the `game_data.json `.

**Comment by ThibautSF** [comment]
As said by @Perhelion 
> PS:
Okay as I suspected, if you read 2h forum comments you find out " (PMM only edit mod order for game, launcher use a different file)"

Launcher order is just visual, if you don't edit your mods with the launcher (that's mean, add or remove a mod from selection and change order of mods in the launcher) the `dlc_load.json` wont be updated. So simply launch the game and it will launch with the PMM order.

Adapt and custom the launcher order with PMM is planed as improvement : #52 
But for now, my goal is to release [ParadoxosModManagerRework](https://github.com/ThibautSF/ParadoxosModManagerRework) (in fact it's almost done, but it's the end of semester with school projects and exams)
