### ISSUE TITLE
Is there a way to apply a sorting option by a mod Version?

### ISSUE THREAD

**Issue by TuxuHolyland** [ThibautSF/ParadoxosModManager#55]
Sorry if this isn't posted in the right place, I'm quite new to these parts. :)

**Comment by ThibautSF** [comment]
Possible duplicate with #25 

Should be more easy now, since i changed a bit how the table view is working.

**Comment by TuxuHolyland** [comment]
I could move the actual row left or right but wasn't able to sort by it while using ParadoxosModManager0.7.1 with Stellaris Shelley 2.5.1.
