### ISSUE TITLE
"The document path is not correct" HoI4 1.8

### ISSUE THREAD

**Issue by AtomicBlastPony** [ThibautSF/ParadoxosModManager#61]
Title says it all. The document path is default and the mod manager generates it correctly, but says it's incorrect when I try to launch it.
Fuck 1.8 and the new launcher.

**Comment by NicolasGrosjean** [comment]
Your document path is something like [...]\Documents\Paradox Interactive\Hearts of Iron IV\ ?

**Comment by AtomicBlastPony** [comment]
Exactly

**Comment by 9bananas** [comment]
i have the same issue for stellaris, just appeared, was working earlier today!

**Comment by ThibautSF** [comment]
Just for information (if anybody come here in the future) :
A game path is detected as "correct" if there is the file "settings.txt" in the target folder.

(this file is generated when you start the launcher at least once, i think... Maybe the game...

**Comment by AtomicBlastPony** [comment]
>Just for information (if anybody come here in the future)
I still had the issue...

Thank you though, tried the mod manager again and it works now.

**Comment by ThibautSF** [comment]
I just test: fresh installs of Paradox games don't create settings.txt files.

I will fix that for the Java 11 version.

**Comment by ThibautSF** [comment]
Repository discontinued

Please re-open in the new repository if needed
https://github.com/ThibautSF/ParadoxosModManager
