### ISSUE TITLE
[Minor] See the current configuration

### ISSUE THREAD

**Issue by NicolasGrosjean** [ThibautSF/ParadoxosModManager#7]
We can imagine to put in some color the current mod configuration in order to know what is it.

I think we need to parse the settings file to get the mod list because the user can modify the activated mods without Paradoxos.

It is a very low priority because the added value is low and the effort is not little.

**Comment by ThibautSF** [comment]
Add : 
- button "import from current"
- onclick event
- refresh method

When click on button : 
- parse settings.txt
- add each mods to the selectedModList (if the file is missing, add to missingMods)
- refresh the table

For now the code is in append mode only, i plan to show a dialogue to choose between : 
- "Replace" : all previous selected mods are unselected before import
- "Append" : keep selected mods and add only the new ones from the import

**Comment by ThibautSF** [comment]
- CK2 seems working now (don't have lot of mods to test)
- language is also get from current config

**Comment by ThibautSF** [comment]
I forgot that 'Fix' close the issue...

**Comment by NicolasGrosjean** [comment]
Sorry, I was very busy.

I confirm it is working for CK2 ... except to get the language

**Comment by NicolasGrosjean** [comment]
The error is when the lanugage is parsed, the last char is missing and like the language is not found, it is set to the default : ENGLISH.
![image](https://user-images.githubusercontent.com/13560473/34453020-c8f4adf0-ed4a-11e7-87ab-88d95a6f6a9f.png)

**Comment by NicolasGrosjean** [comment]
2ng bug:

Some bad lines match with the language code : 
![image](https://user-images.githubusercontent.com/13560473/34453186-9de5a1e8-ed4d-11e7-8b2d-1a7fcc13c2e5.png)

**Comment by ThibautSF** [comment]
So now Replace/Append option dialog

I also add a little "clear" option.

Need some test to be sure before close Issue.

**Comment by NicolasGrosjean** [comment]
I have tested it on Ck2 and HoI4 and I have see no issues.

**Comment by NicolasGrosjean** [comment]
Is there some things to do before to close this issue ?
